before_install: gem install bundler --pre
before_script:
- bundle exec rake test_app
script: DISPLAY=:99.0 bundle exec rspec spec
branches:
  only:
  - 1-3-stable
rvm:
- 2.1.7
notifications:
  slack:
    secure: he/ftnnue2tQp7V3zIJAjpvnv653+geFGsIJcitqQlok/tv8UJkkUxolZTKD8MBNarIXdGnSWDMo4gH7QP3FzHvx2TV5BPwKsU6ShMPcKaDeXlnn9/Z5jQ8zmLO3lEP/saT9tX9SM8HJRScAophk+FIdnGx/YlXQloa1drEAZNA=
